[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "market_data"
version = "0.1.0"
description = "Extract market data from polygon and calculate technical indicators"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

dependencies = [
    "polygon-api-client", 
    "python-dotenv",
    "numpy",
    "pandas",
    "sqlalchemy",
    "psycopg2-binary",
    "tqdm",
    "plotly",
    "financedatabase", # needed for ticker_data
    "ib_insync>=0.9.82", # needed for ibkr_alerts
    "finvizfinance>=0.14.7", # needed for finvix_viewer
]

[project.scripts]
market_data = "market_data.__main__:main"
market_query = "market_query.__main__:main"
ticker_data = "ticker_data.__main__:main"
ibkr_alerts = "ibkr_alerts.__main__:main"
finviz_screener = "finviz_screener.__main__:main"

[tool.setuptools.package-data]
"market_data" = ["sql/*.sql"]
"market_query" = ["sql/*.sql"]
"ibkr_alerts" = ["sql/*.sql"]
